title: Aprendizaje Automático
logo: /assets/img/AI_ML_DL.png
description: Teoría y Práctica para el curso ``Aprendizaje Automático'' (Especialización en Inteligencia de Datos Aplicada)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
