title: Aprendizaje Automático
logo: /assets/img/AI_ML_DL.png
description: Teoría y Práctica para el curso "Aprendizaje Automático" de la Especialización en Inteligencia de Datos Aplicada - Facultad de Informática - Universidad Nacional del Comahue
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
